### ISSUE TITLE
无法生成myConf.conf

### ISSUE THREAD

**Issue by vxxholic** [lizhaode/ShadowRocketConfAuto#1]
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============ RESTART: G:\下载\ShadowRocketConfAuto-master\myConf.py ============
Traceback (most recent call last):
  File "G:\下载\ShadowRocketConfAuto-master\myConf.py", line 10, in <module>
    add.delRulesFromFilebyKeyword()
  File "G:\下载\ShadowRocketConfAuto-master\addGFWtoADfile.py", line 41, in delRulesFromFilebyKeyword
    startIndex = tmpFileContent.index('#KEYWORD\n')
ValueError: '#KEYWORD\n' is not in list

**Comment by lizhaode** [comment]
出现这个问题是因为，原项目中的sr_adb.conf这个文件更改了格式。
而且，这个文件已经不更新了，所以如果有需要，手动更改一下吧
